apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-fastapi
  labels:
    app: server-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-fastapi
  template:
    metadata:
      labels:
        app: server-fastapi
      annotations:
        image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"server-fastapi:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"server-fastapi\")].image"}]'
    spec:
      containers:
        - name: server-fastapi
          image: image-registry.openshift-image-registry.svc:5000/pastepick/server-fastapi:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: 2Gi
              cpu: "1"
            requests:
              memory: 1Gi
              cpu: "500m"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database_url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_name
            - name: ALLAS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: allas_endpoint
            - name: ALLAS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: allas_bucket
            - name: ALLAS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: allas_access_key
            - name: ALLAS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: allas_secret_key
            - name: ALLAS_UPLOAD_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: allas_upload_endpoint
            - name: DB_PORT
              value: "5532"
            - name: DB_HOST
              value: "postgres"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: server-fastapi
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: server-fastapi
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: server-fastapi
spec:
  to:
    kind: Service
    name: server-fastapi
  port:
    targetPort: 8000
  tls:
    termination: edge