apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
      annotations:
        image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"server:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"server\")].image"}]'
    spec:
      containers:
        - name: server
          image: image-registry.openshift-image-registry.svc:5000/pastepick/server:latest
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database_url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_name
            - name: MISTRAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mistral_api_key
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: gemini_api_key
            - name: ALLAS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: allas_endpoint
            - name: ALLAS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: allas_bucket
            - name: ALLAS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: allas_access_key
            - name: ALLAS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: allas_secret_key
            - name: ALLAS_UPLOAD_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: allas_upload_endpoint
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: "postgres"
            - name: FASTAPI_URL
              value: "https://server-fastapi-pastepick.2.rahtiapp.fi/"
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 30
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: server
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: server
spec:
  to:
    kind: Service
    name: server
  port:
    targetPort: 3001
  tls:
    termination: edge